MY_SECRET: ENC[AES256_GCM,data:rCqAy59rSSnKB28UNWx4tuhg,iv:SJ4Ljp6HafCkZbz07XEBzFXRGn1DTT4t0Jn4/jLnZ6Q=,tag:XH3P7Zr3vA1rLjEfM9n0Pg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/kubernetes-283408/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-02-02T17:36:59Z"
          enc: CiQAAs81oF8XwsPH0YXOGHWf+k2vI3iv+GB6A3OSTG4UkefhQEMSSQCClZlPZO6btj2FcSd3PxZkwGf/7osI0buMepTjuNsiH4pIMtCRfDO/rylMx3O+va+FEADWOBduAtzBHs4Ui+FzmgZSOXAo+u0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-13T09:52:16Z"
    mac: ENC[AES256_GCM,data:Mbbn5NPULet0o6WfJSgdxmmgP2vz7azLNbz811QL7bYvwJmHCnUWai3Ew4wdtBIMQX7Bmj/6uUlE5SdDo318dmnvXt+IRLW+o26MZmv7cXO1sIZE3utv187UEIz7YHLQ04+HD7uZ6QYAdzKpvF05WkS8i1t+3e+wxQCFcXTfoKA=,iv:2wBfEPk1HTFzgR7NAJIa5P1lrDLrDSo4DA56kHczEfo=,tag:zlqMJTQmLdGrSg+LkwQB8Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
